using MicroNet.Menu.Api.Data;

namespace MicroNet.Menu.Api.Initializers
{
    public static class DbInitializer
    {
        public static void Initialize(MenuContext context)
        {
            if (!context.Menus.Any())
            {
                //var dashboardMenuId = Guid.NewGuid();       //Dashboard  1
                var administrationMenuId = Guid.NewGuid();  //Administration 2
                var fileMenuId = Guid.NewGuid();            //File  3          
                var operationsMenuId = Guid.NewGuid();      //Operations    4
                var agentManagementMenuId = Guid.NewGuid(); //Agent Management   5
                var mobileTerminalMenuId = Guid.NewGuid();  //POS Terminal - Mobile  6
                var backEndTerminalMenuId = Guid.NewGuid();  //POS Terminal - Back-End  7
                var accountingMenuId = Guid.NewGuid();      //Sundry Accounting 8
                var reportingMenuId = Guid.NewGuid();       //Reporting   9                

                var menus = new List<Entities.Menu>
                {
                    //new Entities.Menu { Id = dashboardMenuId, Name = "Dashboard", Controller = "Home", Action = "Index", Icon = "dashboard-icon", ParentId = Guid.Empty, MenuOrderId = 1 },
                    new Entities.Menu { Id = administrationMenuId, Name = "Administration", Controller = string.Empty, Action = string.Empty, Icon = "M6 5c7.18 0 13 5.82 13 13M6 11a7 7 0 017 7m-6 0a1 1 0 11-2 0 1 1 0 012 0z", ParentId = Guid.Empty, MenuOrderId = 2, UId = string.Empty, CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = fileMenuId, Name = "File", Controller = string.Empty, Action = string.Empty, Icon = "M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z", ParentId = Guid.Empty, MenuOrderId = 3, UId = string.Empty, CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = operationsMenuId, Name = "Operations", Controller = string.Empty, Action = string.Empty, Icon = "M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z", ParentId = Guid.Empty, MenuOrderId = 4, CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", UId = string.Empty, CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = agentManagementMenuId, Name = "Agent Management", Controller = string.Empty, Action = "M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z", Icon = string.Empty, ParentId = Guid.Empty, MenuOrderId = 5, UId = string.Empty, CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = mobileTerminalMenuId, Name = "Mobile Terminal", Controller = string.Empty, Action = string.Empty, Icon = "M3 10h18M3 14h18m-9-4v8m-7 0h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z", ParentId = Guid.Empty, MenuOrderId = 6, UId = string.Empty, CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = backEndTerminalMenuId, Name = "Back-End Terminal", Controller = string.Empty, Action = string.Empty, Icon = "M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4", ParentId = Guid.Empty, MenuOrderId = 7, UId = string.Empty, CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = accountingMenuId, Name = "Accounting", Controller = string.Empty, Action = string.Empty, Icon = "M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z", ParentId = Guid.Empty, MenuOrderId = 8, UId = string.Empty, CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = reportingMenuId, Name = "Reporting", Controller = string.Empty, Action = string.Empty, Icon = "M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10", ParentId = Guid.Empty, MenuOrderId = 9, UId = string.Empty, CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },

                    //Administration Sub Menus
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "User Setup", Controller = "UserSetup", Action = "Index", Icon = string.Empty, ParentId = administrationMenuId, MenuOrderId = 1, UId = "user-setup-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Permission Setup", Controller = "UserPermission", Action = "Index", Icon = string.Empty, ParentId = administrationMenuId, MenuOrderId = 2, UId = "permission-setup-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Password Policy", Controller = "PasswordManagementPolicy", Action = "Index", Icon = string.Empty, ParentId = administrationMenuId, MenuOrderId = 3, UId = "password-policy-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Audit Log", Controller = "AuditLog", Action = "Index", Icon = string.Empty, ParentId = administrationMenuId, MenuOrderId = 4, UId = "audit-log-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "System Setup", Controller = "CompanyModuleSetup", Action = "Index", Icon = string.Empty, ParentId = administrationMenuId, MenuOrderId = 5, UId = "company-module-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    
                    //File Sub Menus
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "User Group Setup", Controller = "UserGroupSetup", Action = "Index", Icon = string.Empty, ParentId = fileMenuId, MenuOrderId = 1, UId = "user-group-setup-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Client Onboarding", Controller = "ClientOnboarding", Action = "Index", Icon = string.Empty, ParentId = fileMenuId, MenuOrderId = 2, UId = "client-onboarding-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Employee Onboarding", Controller = "EmployeeOnboarding", Action = "Index", Icon = string.Empty, ParentId = fileMenuId, MenuOrderId = 3, UId = "employee-onboarding-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "KYC Management", Controller = "KYCManagement", Action = "Index", Icon = string.Empty, ParentId = fileMenuId, MenuOrderId = 4, UId = "kyc-management-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Product Setup", Controller = "ProductSetup", Action = "Index", Icon = string.Empty, ParentId = fileMenuId, MenuOrderId = 5, UId = "product-setup-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Loan Setup", Controller = "LoanSetup", Action = "Index", Icon = string.Empty, ParentId = fileMenuId, MenuOrderId = 6, UId = "loan-setup-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Branch Setup", Controller = "BranchSetup", Action = "Index", Icon = string.Empty, ParentId = fileMenuId, MenuOrderId = 7, UId = "branch-setup-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Branch Termination Rule", Controller = "BranchTerminationRule", Action = "Index", Icon = string.Empty, ParentId = fileMenuId, MenuOrderId = 8, UId = "branch-termination-rule-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Branch Logout", Controller = "BranchLogout", Action = "Index", Icon = string.Empty, ParentId = fileMenuId, MenuOrderId = 9, UId = "branch-logout-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Device Setup", Controller = "DeviceSetup", Action = "Index", Icon = string.Empty, ParentId = fileMenuId, MenuOrderId = 10, UId = "device-setup-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Logout", Controller = "Logout", Action = "Index", Icon = string.Empty, ParentId = fileMenuId, MenuOrderId = 11, UId = "log-out-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "exit", Controller = "exit", Action = "Index", Icon = string.Empty, ParentId = fileMenuId, MenuOrderId = 12, UId = "exit-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Zone", Controller = "Zone", Action = "Index", Icon = string.Empty, ParentId = fileMenuId, MenuOrderId = 13, UId = "zone-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    
                    //Operation Sub Menus
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Revenue Collection", Controller = "RevenueCollection", Action = "Index", Icon = string.Empty, ParentId = operationsMenuId, MenuOrderId = 1, UId = "revenue-collection-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Revenue Reversal", Controller = "RevenueReversal", Action = "Index", Icon = string.Empty, ParentId = operationsMenuId, MenuOrderId = 2, UId = "revenue-reversal-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Interest Distribution", Controller = "InterestDistribution", Action = "Index", Icon = string.Empty, ParentId = operationsMenuId, MenuOrderId = 3, UId = "interest-distribution-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Management Fees", Controller = "ManagementFees", Action = "Index", Icon = string.Empty, ParentId = operationsMenuId, MenuOrderId = 4, UId = "management-fees-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Loan Penalty Charges", Controller = "LoanPenaltyCharges", Action = "Index", Icon = string.Empty, ParentId = operationsMenuId, MenuOrderId = 5, UId = "loan-penalty-charges-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Account Transfer", Controller = "AccountTransfer", Action = "Index", Icon = string.Empty, ParentId = operationsMenuId, MenuOrderId = 6, UId = "account-transfer-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Account Termination", Controller = "AccountTermination", Action = "Index", Icon = string.Empty, ParentId = operationsMenuId, MenuOrderId = 7, UId = "account-termination-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Loan Booking", Controller = "LoanBooking", Action = "Index", Icon = string.Empty, ParentId = operationsMenuId, MenuOrderId = 8, UId = "loan-booking-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Withdrawal Client", Controller = "WithdrawalClient", Action = "Index", Icon = string.Empty, ParentId = operationsMenuId, MenuOrderId = 9, UId = "withdrawal-client-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },

                    //Agent Management Sub Menus
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Agent Account Activation", Controller = "AgentAccountActivation", Action = "Index", Icon = string.Empty, ParentId = agentManagementMenuId, MenuOrderId = 1, UId = "agent-account-activation-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Forget Password", Controller = "ForgetPassword", Action = "Index", Icon = string.Empty, ParentId = agentManagementMenuId, MenuOrderId = 2, UId = "forget-password-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Change Password", Controller = "ChangePassword", Action = "Index", Icon = string.Empty, ParentId = agentManagementMenuId, MenuOrderId = 3, UId = "change-password-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Change Agent Pin", Controller = "ChangeAgentPin", Action = "Index", Icon = string.Empty, ParentId = agentManagementMenuId, MenuOrderId = 4, UId = "change-agent-pin-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Reset Agent Pin", Controller = "ResetAgentPin", Action = "Index", Icon = string.Empty, ParentId = agentManagementMenuId, MenuOrderId = 5, UId = "reset-agent-pin-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },

                    //Mobile Terminal Sub Menus
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Balance Enquiry", Controller = "BalanceEnquiry", Action = "Index", Icon = string.Empty, ParentId = mobileTerminalMenuId, MenuOrderId = 1, UId = "balance-enquiry-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Third Party Deposit", Controller = "ThirdPartyDeposit", Action = "Index", Icon = string.Empty, ParentId = mobileTerminalMenuId, MenuOrderId = 2, UId = "third-party-deposit-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Own Account Deposit", Controller = "OwnAccountDeposit", Action = "Index", Icon = string.Empty, ParentId = mobileTerminalMenuId, MenuOrderId = 3, UId = "own-account-deposit-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },

                    //Back End Terminal Sub Menus
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Balance Enquiry Activity", Controller = "BalanceEnquiryActivity", Action = "Index", Icon = string.Empty, ParentId = backEndTerminalMenuId, MenuOrderId = 1, UId = "balance-enquiry-activity-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Deposit Activity", Controller = "DepositActivity", Action = "Index", Icon = string.Empty, ParentId = backEndTerminalMenuId, MenuOrderId = 2, UId = "deposit-activity-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },

                    //Accounting Sub Menus
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Setup Accounts", Controller = "SetupAccounts", Action = "Index", Icon = string.Empty, ParentId = accountingMenuId, MenuOrderId = 1, UId = "setup-accounts-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Map Expense Account Transaction", Controller = "MapExpenseAccountTransaction", Action = "Index", Icon = string.Empty, ParentId = accountingMenuId, MenuOrderId = 2, UId = "map-expense-account-transaction-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Map Revenue Account Transaction", Controller = "MapRevenueAccountTransaction", Action = "Index", Icon = string.Empty, ParentId = accountingMenuId, MenuOrderId = 3, UId = "map-revenue-account-transaction-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Generate PL Report", Controller = "GeneratePLReport", Action = "Index", Icon = string.Empty, ParentId = accountingMenuId, MenuOrderId = 4, UId = "generate-pl-report-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },

                    //Reporting Sub Menus
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Branch Report", Controller = "Branch", Action = "Index", Icon = string.Empty, ParentId = reportingMenuId, MenuOrderId = 1, UId = "branch-report-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Account Report", Controller = "Accounts", Action = "Index", Icon = string.Empty, ParentId = reportingMenuId, MenuOrderId = 2, UId = "account-report-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Loan Report", Controller = "Loan", Action = "Index", Icon = string.Empty, ParentId = reportingMenuId, MenuOrderId = 3, UId = "loan-report-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now },
                    new Entities.Menu { Id = Guid.NewGuid(), Name = "Transaction Report", Controller = "Transaction", Action = "Index", Icon = string.Empty, ParentId = reportingMenuId, MenuOrderId = 4, UId = "transaction-report-icon", CreatedBy = "1A9C243D-1228-4B83-AC01-D41BB8CC5541", CreatedOn = DateTime.Now, UpdatedBy = "NULL", UpdatedOn = DateTime.Now }
                };

                context.Menus.AddRange(menus);
                context.SaveChanges();
            }
        }
    }
}
