services:
  micronet.user.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=9090
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/devcert.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - ConnectionStrings__UserConnection=Server=micronet.user.db;Database=dma_microNet_db;User Id=sa;Password=Micronet@2025$;Trusted_Connection=False;MultipleActiveResultSets=True;TrustServerCertificate=True
      - ConsulConfig__Address=http://consul:8500
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=admin
      - RabbitMQ__Password=Micronet@2025$
    ports:
      - "1000:8080"
      - "1010:9090"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - micronet.user.db
      - consul
      - rabbitmq
    networks:
      - elk-network

  micronet.branch.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8081
      - ASPNETCORE_HTTPS_PORTS=9091
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/devcert.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - ConnectionStrings__UserConnection=Server=micronet.user.db;Database=dma_microNet_db;User Id=sa;Password=Micronet@2025$;Trusted_Connection=False;MultipleActiveResultSets=True;TrustServerCertificate=True
      - ConsulConfig__Address=http://consul:8500
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=admin
      - RabbitMQ__Password=Micronet@2025$
    ports:
      - "1001:8081"
      - "1011:9091"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - micronet.user.db
      - consul
      - rabbitmq
    networks:
      - elk-network
