CREATE TABLE [employee].[Employees] (
    [Id]                            UNIQUEIDENTIFIER NOT NULL,
    [EmployeeNumber]                NVARCHAR (MAX)   NOT NULL,
    [FirstName]                     NVARCHAR (MAX)   NOT NULL,
    [Surname]                       NVARCHAR (MAX)   NOT NULL,
    [OtherName]                     NVARCHAR (MAX)   NOT NULL,
    [DateOfBirth]                   DATETIME2 (7)    NOT NULL,
    [Age]                           INT              NOT NULL,
    [PhoneNumber]                   NVARCHAR (MAX)   NOT NULL,
    [PhysicalAddress]               NVARCHAR (MAX)   NOT NULL,
    [PostalAddress]                 NVARCHAR (MAX)   NOT NULL,
    [EmailAddress]                  NVARCHAR (MAX)   NOT NULL,
    [SocialMediaAccount]            NVARCHAR (MAX)   NOT NULL,
    [IsSystemUser]                  BIT              NOT NULL,
    [EmployeeType]                  NVARCHAR (MAX)   NOT NULL,
    [BranchId]                      UNIQUEIDENTIFIER NOT NULL,
    [DeviceId]                      UNIQUEIDENTIFIER NOT NULL,
    [ZoneId]                        UNIQUEIDENTIFIER NOT NULL,
    [DateEmployed]                  DATETIME2 (7)    NOT NULL,
    [Picture]                       VARBINARY (MAX)  NOT NULL,
    [NationalId]                    NVARCHAR (MAX)   NOT NULL,
    [TransactionLimit]              DECIMAL (18, 2)  NULL,
    [ContactPerson_Name]            NVARCHAR (MAX)   NOT NULL,
    [ContactPerson_GhanaCard]       NVARCHAR (MAX)   NOT NULL,
    [ContactPerson_PrimaryPhone]    NVARCHAR (MAX)   NOT NULL,
    [ContactPerson_AlternatePhone]  NVARCHAR (MAX)   NOT NULL,
    [ContactPerson_PrimaryEmail]    NVARCHAR (MAX)   NOT NULL,
    [ContactPerson_AlternateEmail]  NVARCHAR (MAX)   NOT NULL,
    [ContactPerson_PhysicalAddress] NVARCHAR (MAX)   NOT NULL,
    [ContactPerson_PostalAddress]   NVARCHAR (MAX)   NOT NULL,
    [ContactPerson_SocialMedia]     NVARCHAR (MAX)   NOT NULL,
    [AuditInfo_CreatedBy]           NVARCHAR (MAX)   NULL,
    [AuditInfo_CreatedAt]           DATETIME2 (7)    NULL,
    [AuditInfo_UpdatedBy]           NVARCHAR (MAX)   NULL,
    [AuditInfo_UpdatedAt]           DATETIME2 (7)    NULL,
    [AuditInfo_DeletedBy]           NVARCHAR (MAX)   NULL,
    [AuditInfo_DeletedAt]           DATETIME2 (7)    NULL,
    [Version]                       INT              NOT NULL,
    CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED ([Id] ASC)
);

