CREATE TABLE [system].[CompanySetups] (
    [Id]                     UNIQUEIDENTIFIER NOT NULL,
    [CompanyName]            NVARCHAR (200)   NOT NULL,
    [CompanyAddress]         NVARCHAR (300)   NOT NULL,
    [RegistrationDate]       DATETIME2 (7)    NOT NULL,
    [ContactFirstName]       NVARCHAR (100)   NOT NULL,
    [ContactLastName]        NVARCHAR (100)   NOT NULL,
    [ContactEmail]           NVARCHAR (100)   NOT NULL,
    [ContactPhone]           NVARCHAR (50)    NOT NULL,
    [OfficialEmail]          NVARCHAR (100)   NOT NULL,
    [OfficialPhoneNumber]    NVARCHAR (50)    NOT NULL,
    [YearOfRegistration]     NVARCHAR (10)    NOT NULL,
    [SSN]                    NVARCHAR (50)    NOT NULL,
    [TIN]                    NVARCHAR (50)    NOT NULL,
    [Prefix]                 NVARCHAR (20)    NOT NULL,
    [LogoFileName]           NVARCHAR (200)   NULL,
    [LogoContent]            VARBINARY (MAX)  NULL,
    [CoreBanking]            BIT              NOT NULL,
    [TelcoIntegration]       BIT              NOT NULL,
    [PaymentGateway]         BIT              NOT NULL,
    [SftpPath]               NVARCHAR (200)   NULL,
    [ExportPath]             NVARCHAR (200)   NULL,
    [BatchImport]            BIT              NOT NULL,
    [NotificationMode]       INT              NOT NULL,
    [NotificationRecipients] NVARCHAR (500)   NOT NULL,
    [UseMakerChecker]        BIT              NOT NULL,
    [RequireLimit]           BIT              NOT NULL,
    [Version]                INT              NOT NULL,
    [AuditInfo_CreatedAt]    DATETIME2 (7)    NULL,
    [AuditInfo_CreatedBy]    NVARCHAR (100)   NULL,
    [AuditInfo_UpdatedAt]    DATETIME2 (7)    NULL,
    [AuditInfo_UpdatedBy]    NVARCHAR (100)   NULL,
    CONSTRAINT [PK_CompanySetups] PRIMARY KEY CLUSTERED ([Id] ASC)
);

